services:
  chatapp-mysql:
    image: mysql:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: chatapp
      MYSQL_USER: chatapp
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - chatapp_auth_data:/var/lib/mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    networks:
      - chatapp_network


volumes:
  chatapp_auth_data:

networks:
  chatapp_network:
    driver: bridge
